Add `Base.vec(M::MatElem)`
Nemocas/AbstractAlgebra.jl pull request #1614
Opened 2024-02-19 11:18 UTC by lgoettgens

The code originates in https://github.com/oscar-system/Oscar.jl/blob/597398c594796cd2abbd8749977cb3f2a20eefb2/experimental/GModule/GModule.jl#L1451, but I want to use it in other parts of Oscar, that should not depend on experimental. So the cleanest solution is to add it here.
Note that this code currently operates in column-wise fashion (should this be changed?)

To reduce any conflicts in Oscar, it would be easiest to include this in the next breaking release, and then remove the corresponding things in https://github.com/oscar-system/Oscar.jl/blob/597398c594796cd2abbd8749977cb3f2a20eefb2/experimental/GModule/GModule.jl#L1451.

2024-02-19 11:49 UTC, fingolfin approved these changes

2024-02-19 11:49 UTC, fingolfin commented on src/Matrix.jl
How about also adding this, which is also from the same source:
```suggestion

#to bypass the vec(collect(M)) which copies twice
function Base.vec(M::Generic.Mat)
  return vec(M.entries)
end

```

2024-02-19 11:54 UTC, thofma requested changes
Not clear to me if we want this.

2024-02-19 12:31 UTC, lgoettgens commented
> Not clear to me if we want this.

If we don't want this, this shouldn't be in Oscar as well (pinging @fieker).

But I think we should definitely have a cheap way to convert a matrix to a vector

2024-02-19 13:14 UTC, thofma commented
1. We should not have it in this form for the same reason we don't have linear indexing: It is ambiguous.
2. Is violates `A == matrix(A, nrows(A), ncols(A), vec(A))`
3. If it exists, it must be a view/reshape.

2024-02-19 13:15 UTC, thofma commented
I am happy to rename it to `_vec` in Oscar and postpone this discussion.

2024-10-07 20:07 UTC, fingolfin commented
This seems to be controversial and I also don't see a good way to implement this efficiently without a lot of effort. So is this really worth pursuing?

If @lgoettgens still has need, perhaps we should discuss it during triage?

2024-10-07 21:03 UTC, closed without merging

2024-10-07 21:04 UTC, lgoettgens commented
Iirc we resolved the problem in a different way